//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GK.WebServices.REST.CrmService.DataPortApi {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MessageServicesSoap", Namespace="http://sms.dataport.com.tr/")]
    public partial class MessageServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RegisterOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendTCNOSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendWapPushOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendTAXNOSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInboxMessagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateSendGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendFileSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendTCNOSearchGSMOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendTCNOConfirmGSMOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelMessagesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MessageServices() {
            this.Url = global::GK.WebServices.REST.CrmService.Properties.Settings.Default.GK_WebServices_REST_CrmService_DataPortApi_MessageServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RegisterCompletedEventHandler RegisterCompleted;
        
        /// <remarks/>
        public event SendSMSCompletedEventHandler SendSMSCompleted;
        
        /// <remarks/>
        public event SendTCNOSMSCompletedEventHandler SendTCNOSMSCompleted;
        
        /// <remarks/>
        public event SendWapPushCompletedEventHandler SendWapPushCompleted;
        
        /// <remarks/>
        public event SendMMSCompletedEventHandler SendMMSCompleted;
        
        /// <remarks/>
        public event SendTAXNOSMSCompletedEventHandler SendTAXNOSMSCompleted;
        
        /// <remarks/>
        public event GetInboxMessagesCompletedEventHandler GetInboxMessagesCompleted;
        
        /// <remarks/>
        public event CreateSendGroupCompletedEventHandler CreateSendGroupCompleted;
        
        /// <remarks/>
        public event SendFileSMSCompletedEventHandler SendFileSMSCompleted;
        
        /// <remarks/>
        public event SendTCNOSearchGSMCompletedEventHandler SendTCNOSearchGSMCompleted;
        
        /// <remarks/>
        public event SendTCNOConfirmGSMCompletedEventHandler SendTCNOConfirmGSMCompleted;
        
        /// <remarks/>
        public event CancelMessagesCompletedEventHandler CancelMessagesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sms.dataport.com.tr/Register", RequestNamespace="http://sms.dataport.com.tr/", ResponseNamespace="http://sms.dataport.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Register(Session Session) {
            object[] results = this.Invoke("Register", new object[] {
                        Session});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterAsync(Session Session) {
            this.RegisterAsync(Session, null);
        }
        
        /// <remarks/>
        public void RegisterAsync(Session Session, object userState) {
            if ((this.RegisterOperationCompleted == null)) {
                this.RegisterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterOperationCompleted);
            }
            this.InvokeAsync("Register", new object[] {
                        Session}, this.RegisterOperationCompleted, userState);
        }
        
        private void OnRegisterOperationCompleted(object arg) {
            if ((this.RegisterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterCompleted(this, new RegisterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sms.dataport.com.tr/SendSMS", RequestNamespace="http://sms.dataport.com.tr/", ResponseNamespace="http://sms.dataport.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendMessageResponse SendSMS(SendSMSRequest SendSMSRequest) {
            object[] results = this.Invoke("SendSMS", new object[] {
                        SendSMSRequest});
            return ((SendMessageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMSAsync(SendSMSRequest SendSMSRequest) {
            this.SendSMSAsync(SendSMSRequest, null);
        }
        
        /// <remarks/>
        public void SendSMSAsync(SendSMSRequest SendSMSRequest, object userState) {
            if ((this.SendSMSOperationCompleted == null)) {
                this.SendSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMSOperationCompleted);
            }
            this.InvokeAsync("SendSMS", new object[] {
                        SendSMSRequest}, this.SendSMSOperationCompleted, userState);
        }
        
        private void OnSendSMSOperationCompleted(object arg) {
            if ((this.SendSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMSCompleted(this, new SendSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sms.dataport.com.tr/SendTCNOSMS", RequestNamespace="http://sms.dataport.com.tr/", ResponseNamespace="http://sms.dataport.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendMessageResponse SendTCNOSMS(SendTCNoSMSRequest SendTCNoSMSRequest) {
            object[] results = this.Invoke("SendTCNOSMS", new object[] {
                        SendTCNoSMSRequest});
            return ((SendMessageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SendTCNOSMSAsync(SendTCNoSMSRequest SendTCNoSMSRequest) {
            this.SendTCNOSMSAsync(SendTCNoSMSRequest, null);
        }
        
        /// <remarks/>
        public void SendTCNOSMSAsync(SendTCNoSMSRequest SendTCNoSMSRequest, object userState) {
            if ((this.SendTCNOSMSOperationCompleted == null)) {
                this.SendTCNOSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendTCNOSMSOperationCompleted);
            }
            this.InvokeAsync("SendTCNOSMS", new object[] {
                        SendTCNoSMSRequest}, this.SendTCNOSMSOperationCompleted, userState);
        }
        
        private void OnSendTCNOSMSOperationCompleted(object arg) {
            if ((this.SendTCNOSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendTCNOSMSCompleted(this, new SendTCNOSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sms.dataport.com.tr/SendWapPush", RequestNamespace="http://sms.dataport.com.tr/", ResponseNamespace="http://sms.dataport.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendMessageResponse SendWapPush(SendWappushRequest SendWappushRequest) {
            object[] results = this.Invoke("SendWapPush", new object[] {
                        SendWappushRequest});
            return ((SendMessageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SendWapPushAsync(SendWappushRequest SendWappushRequest) {
            this.SendWapPushAsync(SendWappushRequest, null);
        }
        
        /// <remarks/>
        public void SendWapPushAsync(SendWappushRequest SendWappushRequest, object userState) {
            if ((this.SendWapPushOperationCompleted == null)) {
                this.SendWapPushOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendWapPushOperationCompleted);
            }
            this.InvokeAsync("SendWapPush", new object[] {
                        SendWappushRequest}, this.SendWapPushOperationCompleted, userState);
        }
        
        private void OnSendWapPushOperationCompleted(object arg) {
            if ((this.SendWapPushCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendWapPushCompleted(this, new SendWapPushCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sms.dataport.com.tr/SendMMS", RequestNamespace="http://sms.dataport.com.tr/", ResponseNamespace="http://sms.dataport.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendMMSResponse SendMMS(SendMMSRequest SendMMSRequest) {
            object[] results = this.Invoke("SendMMS", new object[] {
                        SendMMSRequest});
            return ((SendMMSResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SendMMSAsync(SendMMSRequest SendMMSRequest) {
            this.SendMMSAsync(SendMMSRequest, null);
        }
        
        /// <remarks/>
        public void SendMMSAsync(SendMMSRequest SendMMSRequest, object userState) {
            if ((this.SendMMSOperationCompleted == null)) {
                this.SendMMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMMSOperationCompleted);
            }
            this.InvokeAsync("SendMMS", new object[] {
                        SendMMSRequest}, this.SendMMSOperationCompleted, userState);
        }
        
        private void OnSendMMSOperationCompleted(object arg) {
            if ((this.SendMMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMMSCompleted(this, new SendMMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sms.dataport.com.tr/SendTAXNOSMS", RequestNamespace="http://sms.dataport.com.tr/", ResponseNamespace="http://sms.dataport.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendMessageResponse SendTAXNOSMS(SendTaxNoSMSRequest SendTaxNoSMSRequest) {
            object[] results = this.Invoke("SendTAXNOSMS", new object[] {
                        SendTaxNoSMSRequest});
            return ((SendMessageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SendTAXNOSMSAsync(SendTaxNoSMSRequest SendTaxNoSMSRequest) {
            this.SendTAXNOSMSAsync(SendTaxNoSMSRequest, null);
        }
        
        /// <remarks/>
        public void SendTAXNOSMSAsync(SendTaxNoSMSRequest SendTaxNoSMSRequest, object userState) {
            if ((this.SendTAXNOSMSOperationCompleted == null)) {
                this.SendTAXNOSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendTAXNOSMSOperationCompleted);
            }
            this.InvokeAsync("SendTAXNOSMS", new object[] {
                        SendTaxNoSMSRequest}, this.SendTAXNOSMSOperationCompleted, userState);
        }
        
        private void OnSendTAXNOSMSOperationCompleted(object arg) {
            if ((this.SendTAXNOSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendTAXNOSMSCompleted(this, new SendTAXNOSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sms.dataport.com.tr/GetInboxMessages", RequestNamespace="http://sms.dataport.com.tr/", ResponseNamespace="http://sms.dataport.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InboxResponse GetInboxMessages(InboxRequest InboxRequest) {
            object[] results = this.Invoke("GetInboxMessages", new object[] {
                        InboxRequest});
            return ((InboxResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetInboxMessagesAsync(InboxRequest InboxRequest) {
            this.GetInboxMessagesAsync(InboxRequest, null);
        }
        
        /// <remarks/>
        public void GetInboxMessagesAsync(InboxRequest InboxRequest, object userState) {
            if ((this.GetInboxMessagesOperationCompleted == null)) {
                this.GetInboxMessagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInboxMessagesOperationCompleted);
            }
            this.InvokeAsync("GetInboxMessages", new object[] {
                        InboxRequest}, this.GetInboxMessagesOperationCompleted, userState);
        }
        
        private void OnGetInboxMessagesOperationCompleted(object arg) {
            if ((this.GetInboxMessagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInboxMessagesCompleted(this, new GetInboxMessagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sms.dataport.com.tr/CreateSendGroup", RequestNamespace="http://sms.dataport.com.tr/", ResponseNamespace="http://sms.dataport.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CreateGroupResponse CreateSendGroup(CreateGroupRequest CreateGroupRequest) {
            object[] results = this.Invoke("CreateSendGroup", new object[] {
                        CreateGroupRequest});
            return ((CreateGroupResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CreateSendGroupAsync(CreateGroupRequest CreateGroupRequest) {
            this.CreateSendGroupAsync(CreateGroupRequest, null);
        }
        
        /// <remarks/>
        public void CreateSendGroupAsync(CreateGroupRequest CreateGroupRequest, object userState) {
            if ((this.CreateSendGroupOperationCompleted == null)) {
                this.CreateSendGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateSendGroupOperationCompleted);
            }
            this.InvokeAsync("CreateSendGroup", new object[] {
                        CreateGroupRequest}, this.CreateSendGroupOperationCompleted, userState);
        }
        
        private void OnCreateSendGroupOperationCompleted(object arg) {
            if ((this.CreateSendGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateSendGroupCompleted(this, new CreateSendGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sms.dataport.com.tr/SendFileSMS", RequestNamespace="http://sms.dataport.com.tr/", ResponseNamespace="http://sms.dataport.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FileSMSResponse SendFileSMS(FileSMSRequest FileSMSRequest, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] File) {
            object[] results = this.Invoke("SendFileSMS", new object[] {
                        FileSMSRequest,
                        File});
            return ((FileSMSResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SendFileSMSAsync(FileSMSRequest FileSMSRequest, byte[] File) {
            this.SendFileSMSAsync(FileSMSRequest, File, null);
        }
        
        /// <remarks/>
        public void SendFileSMSAsync(FileSMSRequest FileSMSRequest, byte[] File, object userState) {
            if ((this.SendFileSMSOperationCompleted == null)) {
                this.SendFileSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendFileSMSOperationCompleted);
            }
            this.InvokeAsync("SendFileSMS", new object[] {
                        FileSMSRequest,
                        File}, this.SendFileSMSOperationCompleted, userState);
        }
        
        private void OnSendFileSMSOperationCompleted(object arg) {
            if ((this.SendFileSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendFileSMSCompleted(this, new SendFileSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sms.dataport.com.tr/SendTCNOSearchGSM", RequestNamespace="http://sms.dataport.com.tr/", ResponseNamespace="http://sms.dataport.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendMessageResponse SendTCNOSearchGSM(TckGsmSearchRequest TckGsmSearchRequest) {
            object[] results = this.Invoke("SendTCNOSearchGSM", new object[] {
                        TckGsmSearchRequest});
            return ((SendMessageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SendTCNOSearchGSMAsync(TckGsmSearchRequest TckGsmSearchRequest) {
            this.SendTCNOSearchGSMAsync(TckGsmSearchRequest, null);
        }
        
        /// <remarks/>
        public void SendTCNOSearchGSMAsync(TckGsmSearchRequest TckGsmSearchRequest, object userState) {
            if ((this.SendTCNOSearchGSMOperationCompleted == null)) {
                this.SendTCNOSearchGSMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendTCNOSearchGSMOperationCompleted);
            }
            this.InvokeAsync("SendTCNOSearchGSM", new object[] {
                        TckGsmSearchRequest}, this.SendTCNOSearchGSMOperationCompleted, userState);
        }
        
        private void OnSendTCNOSearchGSMOperationCompleted(object arg) {
            if ((this.SendTCNOSearchGSMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendTCNOSearchGSMCompleted(this, new SendTCNOSearchGSMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sms.dataport.com.tr/SendTCNOConfirmGSM", RequestNamespace="http://sms.dataport.com.tr/", ResponseNamespace="http://sms.dataport.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendMessageResponse SendTCNOConfirmGSM(TckGsmConfirmRequest TckGsmConfirmRequest) {
            object[] results = this.Invoke("SendTCNOConfirmGSM", new object[] {
                        TckGsmConfirmRequest});
            return ((SendMessageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SendTCNOConfirmGSMAsync(TckGsmConfirmRequest TckGsmConfirmRequest) {
            this.SendTCNOConfirmGSMAsync(TckGsmConfirmRequest, null);
        }
        
        /// <remarks/>
        public void SendTCNOConfirmGSMAsync(TckGsmConfirmRequest TckGsmConfirmRequest, object userState) {
            if ((this.SendTCNOConfirmGSMOperationCompleted == null)) {
                this.SendTCNOConfirmGSMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendTCNOConfirmGSMOperationCompleted);
            }
            this.InvokeAsync("SendTCNOConfirmGSM", new object[] {
                        TckGsmConfirmRequest}, this.SendTCNOConfirmGSMOperationCompleted, userState);
        }
        
        private void OnSendTCNOConfirmGSMOperationCompleted(object arg) {
            if ((this.SendTCNOConfirmGSMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendTCNOConfirmGSMCompleted(this, new SendTCNOConfirmGSMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sms.dataport.com.tr/CancelMessages", RequestNamespace="http://sms.dataport.com.tr/", ResponseNamespace="http://sms.dataport.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CancelMessagesResponse CancelMessages(CancelMessagesRequest CancelMessagesRequest) {
            object[] results = this.Invoke("CancelMessages", new object[] {
                        CancelMessagesRequest});
            return ((CancelMessagesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CancelMessagesAsync(CancelMessagesRequest CancelMessagesRequest) {
            this.CancelMessagesAsync(CancelMessagesRequest, null);
        }
        
        /// <remarks/>
        public void CancelMessagesAsync(CancelMessagesRequest CancelMessagesRequest, object userState) {
            if ((this.CancelMessagesOperationCompleted == null)) {
                this.CancelMessagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelMessagesOperationCompleted);
            }
            this.InvokeAsync("CancelMessages", new object[] {
                        CancelMessagesRequest}, this.CancelMessagesOperationCompleted, userState);
        }
        
        private void OnCancelMessagesOperationCompleted(object arg) {
            if ((this.CancelMessagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelMessagesCompleted(this, new CancelMessagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class Session {
        
        private string accountNumberField;
        
        private string userNameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class CanceledMessage {
        
        private string statusField;
        
        private string messageIDField;
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class CancelMessagesResponse {
        
        private CanceledMessage[] canceledMessageField;
        
        private string errorField;
        
        /// <remarks/>
        public CanceledMessage[] CanceledMessage {
            get {
                return this.canceledMessageField;
            }
            set {
                this.canceledMessageField = value;
            }
        }
        
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class CancelID {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class CancelMessagesRequest {
        
        private CancelID[] cancelIDsField;
        
        private string sessionIDField;
        
        /// <remarks/>
        public CancelID[] CancelIDs {
            get {
                return this.cancelIDsField;
            }
            set {
                this.cancelIDsField = value;
            }
        }
        
        /// <remarks/>
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class TckGsmConfirmRequest {
        
        private string sessionIDField;
        
        private Operators operatorField;
        
        private string orginatorField;
        
        private string shortNumberField;
        
        private TCNO[] tCNoListField;
        
        private GSM[] gSMListField;
        
        /// <remarks/>
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        public Operators Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        public string Orginator {
            get {
                return this.orginatorField;
            }
            set {
                this.orginatorField = value;
            }
        }
        
        /// <remarks/>
        public string ShortNumber {
            get {
                return this.shortNumberField;
            }
            set {
                this.shortNumberField = value;
            }
        }
        
        /// <remarks/>
        public TCNO[] TCNoList {
            get {
                return this.tCNoListField;
            }
            set {
                this.tCNoListField = value;
            }
        }
        
        /// <remarks/>
        public GSM[] GSMList {
            get {
                return this.gSMListField;
            }
            set {
                this.gSMListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public enum Operators {
        
        /// <remarks/>
        Turkcell,
        
        /// <remarks/>
        Avea,
        
        /// <remarks/>
        Vodafone,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class TCNO {
        
        private string valueField;
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class GSM {
        
        private string valueField;
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class TckGsmSearchRequest {
        
        private string sessionIDField;
        
        private Operators operatorField;
        
        private string orginatorField;
        
        private string shortNumberField;
        
        private TCNO[] tCNoListField;
        
        /// <remarks/>
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        public Operators Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        public string Orginator {
            get {
                return this.orginatorField;
            }
            set {
                this.orginatorField = value;
            }
        }
        
        /// <remarks/>
        public string ShortNumber {
            get {
                return this.shortNumberField;
            }
            set {
                this.shortNumberField = value;
            }
        }
        
        /// <remarks/>
        public TCNO[] TCNoList {
            get {
                return this.tCNoListField;
            }
            set {
                this.tCNoListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class FileSMSResponse {
        
        private string resultField;
        
        private string groupIDField;
        
        private string fileIDField;
        
        /// <remarks/>
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string GroupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        public string FileID {
            get {
                return this.fileIDField;
            }
            set {
                this.fileIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class FileSMSRequest {
        
        private string sessionIDField;
        
        private Operators operatorField;
        
        private string orginatorField;
        
        private string shortNumberField;
        
        private Unicode isunicodeField;
        
        private string sendDateField;
        
        private string deleteDateField;
        
        private string messageField;
        
        private FileControl controlTypeField;
        
        private string fileNameField;
        
        /// <remarks/>
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        public Operators Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        public string Orginator {
            get {
                return this.orginatorField;
            }
            set {
                this.orginatorField = value;
            }
        }
        
        /// <remarks/>
        public string ShortNumber {
            get {
                return this.shortNumberField;
            }
            set {
                this.shortNumberField = value;
            }
        }
        
        /// <remarks/>
        public Unicode Isunicode {
            get {
                return this.isunicodeField;
            }
            set {
                this.isunicodeField = value;
            }
        }
        
        /// <remarks/>
        public string SendDate {
            get {
                return this.sendDateField;
            }
            set {
                this.sendDateField = value;
            }
        }
        
        /// <remarks/>
        public string DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public FileControl ControlType {
            get {
                return this.controlTypeField;
            }
            set {
                this.controlTypeField = value;
            }
        }
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public enum Unicode {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public enum FileControl {
        
        /// <remarks/>
        UnControl,
        
        /// <remarks/>
        Size,
        
        /// <remarks/>
        Name,
        
        /// <remarks/>
        Size_Name,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class CreateGroupResponse {
        
        private string resultField;
        
        private string groupIDField;
        
        /// <remarks/>
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string GroupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class CreateGroupRequest {
        
        private string sessionIDField;
        
        private string groupNameField;
        
        /// <remarks/>
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        public string GroupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class InboxMessage {
        
        private string messageIDField;
        
        private string senderField;
        
        private string sourceNumberField;
        
        private string messageField;
        
        private string sendDateField;
        
        private string stateField;
        
        private string operatorField;
        
        /// <remarks/>
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        public string SourceNumber {
            get {
                return this.sourceNumberField;
            }
            set {
                this.sourceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string SendDate {
            get {
                return this.sendDateField;
            }
            set {
                this.sendDateField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class InboxResponse {
        
        private string errorField;
        
        private InboxMessage[] inboxMessageListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public InboxMessage[] InboxMessageList {
            get {
                return this.inboxMessageListField;
            }
            set {
                this.inboxMessageListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class InboxRequest {
        
        private string lastDateField;
        
        private string firstDateField;
        
        private MessageState stateField;
        
        private Operators operatorField;
        
        private string prefixField;
        
        private string shortNumberField;
        
        private string sessionIDField;
        
        /// <remarks/>
        public string LastDate {
            get {
                return this.lastDateField;
            }
            set {
                this.lastDateField = value;
            }
        }
        
        /// <remarks/>
        public string FirstDate {
            get {
                return this.firstDateField;
            }
            set {
                this.firstDateField = value;
            }
        }
        
        /// <remarks/>
        public MessageState State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public Operators Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        public string Prefix {
            get {
                return this.prefixField;
            }
            set {
                this.prefixField = value;
            }
        }
        
        /// <remarks/>
        public string ShortNumber {
            get {
                return this.shortNumberField;
            }
            set {
                this.shortNumberField = value;
            }
        }
        
        /// <remarks/>
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public enum MessageState {
        
        /// <remarks/>
        Read,
        
        /// <remarks/>
        Unread,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class TAXNO {
        
        private string valueField;
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class TAXMessageList {
        
        private TAXNO[] tAXNOListField;
        
        private Content[] contentListField;
        
        /// <remarks/>
        public TAXNO[] TAXNOList {
            get {
                return this.tAXNOListField;
            }
            set {
                this.tAXNOListField = value;
            }
        }
        
        /// <remarks/>
        public Content[] ContentList {
            get {
                return this.contentListField;
            }
            set {
                this.contentListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class Content {
        
        private string valueField;
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class SendTaxNoSMSRequest {
        
        private string sessionIDField;
        
        private Operators operatorField;
        
        private string groupIDField;
        
        private string orginatorField;
        
        private string shortNumberField;
        
        private Unicode isunicodeField;
        
        private string sendDateField;
        
        private string deleteDateField;
        
        private TAXMessageList taxMessageListField;
        
        /// <remarks/>
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        public Operators Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        public string GroupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        public string Orginator {
            get {
                return this.orginatorField;
            }
            set {
                this.orginatorField = value;
            }
        }
        
        /// <remarks/>
        public string ShortNumber {
            get {
                return this.shortNumberField;
            }
            set {
                this.shortNumberField = value;
            }
        }
        
        /// <remarks/>
        public Unicode Isunicode {
            get {
                return this.isunicodeField;
            }
            set {
                this.isunicodeField = value;
            }
        }
        
        /// <remarks/>
        public string SendDate {
            get {
                return this.sendDateField;
            }
            set {
                this.sendDateField = value;
            }
        }
        
        /// <remarks/>
        public string DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
        
        /// <remarks/>
        public TAXMessageList TaxMessageList {
            get {
                return this.taxMessageListField;
            }
            set {
                this.taxMessageListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class SendMMSResponse {
        
        private string mMSFileIDField;
        
        private Result[] resultsField;
        
        private string errorField;
        
        /// <remarks/>
        public string MMSFileID {
            get {
                return this.mMSFileIDField;
            }
            set {
                this.mMSFileIDField = value;
            }
        }
        
        /// <remarks/>
        public Result[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
        
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class Result {
        
        private string messageIDField;
        
        private string statusField;
        
        /// <remarks/>
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class MMSContent {
        
        private byte[] mMSFileField;
        
        private string fileNameField;
        
        private string subjectField;
        
        private string messageField;
        
        private string smilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] MMSFile {
            get {
                return this.mMSFileField;
            }
            set {
                this.mMSFileField = value;
            }
        }
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string Smil {
            get {
                return this.smilField;
            }
            set {
                this.smilField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class SendMMSRequest {
        
        private string sessionIDField;
        
        private Operators operatorField;
        
        private string groupIDField;
        
        private string orginatorField;
        
        private string shortNumberField;
        
        private string sendDateField;
        
        private string deleteDateField;
        
        private GSM[] gSMListField;
        
        private string fileIDField;
        
        private MMSContent mMSContentField;
        
        /// <remarks/>
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        public Operators Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        public string GroupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        public string Orginator {
            get {
                return this.orginatorField;
            }
            set {
                this.orginatorField = value;
            }
        }
        
        /// <remarks/>
        public string ShortNumber {
            get {
                return this.shortNumberField;
            }
            set {
                this.shortNumberField = value;
            }
        }
        
        /// <remarks/>
        public string SendDate {
            get {
                return this.sendDateField;
            }
            set {
                this.sendDateField = value;
            }
        }
        
        /// <remarks/>
        public string DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
        
        /// <remarks/>
        public GSM[] GSMList {
            get {
                return this.gSMListField;
            }
            set {
                this.gSMListField = value;
            }
        }
        
        /// <remarks/>
        public string FileID {
            get {
                return this.fileIDField;
            }
            set {
                this.fileIDField = value;
            }
        }
        
        /// <remarks/>
        public MMSContent MMSContent {
            get {
                return this.mMSContentField;
            }
            set {
                this.mMSContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class WPContent {
        
        private string uRLField;
        
        private string indicatorField;
        
        /// <remarks/>
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
        
        /// <remarks/>
        public string Indicator {
            get {
                return this.indicatorField;
            }
            set {
                this.indicatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class WPList {
        
        private GSM[] gSMListField;
        
        private WPContent[] wPContentListField;
        
        /// <remarks/>
        public GSM[] GSMList {
            get {
                return this.gSMListField;
            }
            set {
                this.gSMListField = value;
            }
        }
        
        /// <remarks/>
        public WPContent[] WPContentList {
            get {
                return this.wPContentListField;
            }
            set {
                this.wPContentListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class SendWappushRequest {
        
        private string sessionIDField;
        
        private Operators operatorField;
        
        private string groupIDField;
        
        private string orginatorField;
        
        private string shortNumberField;
        
        private string sendDateField;
        
        private string deleteDateField;
        
        private WPList wPListField;
        
        /// <remarks/>
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        public Operators Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        public string GroupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        public string Orginator {
            get {
                return this.orginatorField;
            }
            set {
                this.orginatorField = value;
            }
        }
        
        /// <remarks/>
        public string ShortNumber {
            get {
                return this.shortNumberField;
            }
            set {
                this.shortNumberField = value;
            }
        }
        
        /// <remarks/>
        public string SendDate {
            get {
                return this.sendDateField;
            }
            set {
                this.sendDateField = value;
            }
        }
        
        /// <remarks/>
        public string DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
        
        /// <remarks/>
        public WPList WPList {
            get {
                return this.wPListField;
            }
            set {
                this.wPListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class TCMessageList {
        
        private TCNO[] tCNOListField;
        
        private Content[] contentListField;
        
        /// <remarks/>
        public TCNO[] TCNOList {
            get {
                return this.tCNOListField;
            }
            set {
                this.tCNOListField = value;
            }
        }
        
        /// <remarks/>
        public Content[] ContentList {
            get {
                return this.contentListField;
            }
            set {
                this.contentListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class SendTCNoSMSRequest {
        
        private string sessionIDField;
        
        private Operators operatorField;
        
        private string groupIDField;
        
        private string orginatorField;
        
        private string shortNumberField;
        
        private Unicode isunicodeField;
        
        private string sendDateField;
        
        private string deleteDateField;
        
        private TCMessageList tCMessageListField;
        
        /// <remarks/>
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        public Operators Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        public string GroupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        public string Orginator {
            get {
                return this.orginatorField;
            }
            set {
                this.orginatorField = value;
            }
        }
        
        /// <remarks/>
        public string ShortNumber {
            get {
                return this.shortNumberField;
            }
            set {
                this.shortNumberField = value;
            }
        }
        
        /// <remarks/>
        public Unicode Isunicode {
            get {
                return this.isunicodeField;
            }
            set {
                this.isunicodeField = value;
            }
        }
        
        /// <remarks/>
        public string SendDate {
            get {
                return this.sendDateField;
            }
            set {
                this.sendDateField = value;
            }
        }
        
        /// <remarks/>
        public string DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
        
        /// <remarks/>
        public TCMessageList TCMessageList {
            get {
                return this.tCMessageListField;
            }
            set {
                this.tCMessageListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class SendMessageResponse {
        
        private Result[] resultsField;
        
        private string errorField;
        
        /// <remarks/>
        public Result[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
        
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class MessageList {
        
        private GSM[] gSMListField;
        
        private Content[] contentListField;
        
        /// <remarks/>
        public GSM[] GSMList {
            get {
                return this.gSMListField;
            }
            set {
                this.gSMListField = value;
            }
        }
        
        /// <remarks/>
        public Content[] ContentList {
            get {
                return this.contentListField;
            }
            set {
                this.contentListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.dataport.com.tr/")]
    public partial class SendSMSRequest {
        
        private string sessionIDField;
        
        private Operators operatorField;
        
        private string groupIDField;
        
        private string orginatorField;
        
        private string shortNumberField;
        
        private Unicode isunicodeField;
        
        private string sendDateField;
        
        private string deleteDateField;
        
        private MessageList messageListField;
        
        /// <remarks/>
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        public Operators Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        public string GroupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        public string Orginator {
            get {
                return this.orginatorField;
            }
            set {
                this.orginatorField = value;
            }
        }
        
        /// <remarks/>
        public string ShortNumber {
            get {
                return this.shortNumberField;
            }
            set {
                this.shortNumberField = value;
            }
        }
        
        /// <remarks/>
        public Unicode Isunicode {
            get {
                return this.isunicodeField;
            }
            set {
                this.isunicodeField = value;
            }
        }
        
        /// <remarks/>
        public string SendDate {
            get {
                return this.sendDateField;
            }
            set {
                this.sendDateField = value;
            }
        }
        
        /// <remarks/>
        public string DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
        
        /// <remarks/>
        public MessageList MessageList {
            get {
                return this.messageListField;
            }
            set {
                this.messageListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RegisterCompletedEventHandler(object sender, RegisterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SendSMSCompletedEventHandler(object sender, SendSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendMessageResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendMessageResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SendTCNOSMSCompletedEventHandler(object sender, SendTCNOSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendTCNOSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendTCNOSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendMessageResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendMessageResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SendWapPushCompletedEventHandler(object sender, SendWapPushCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendWapPushCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendWapPushCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendMessageResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendMessageResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SendMMSCompletedEventHandler(object sender, SendMMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendMMSResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendMMSResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SendTAXNOSMSCompletedEventHandler(object sender, SendTAXNOSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendTAXNOSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendTAXNOSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendMessageResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendMessageResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetInboxMessagesCompletedEventHandler(object sender, GetInboxMessagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInboxMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInboxMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InboxResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InboxResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CreateSendGroupCompletedEventHandler(object sender, CreateSendGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateSendGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateSendGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreateGroupResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreateGroupResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SendFileSMSCompletedEventHandler(object sender, SendFileSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendFileSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendFileSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FileSMSResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FileSMSResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SendTCNOSearchGSMCompletedEventHandler(object sender, SendTCNOSearchGSMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendTCNOSearchGSMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendTCNOSearchGSMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendMessageResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendMessageResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SendTCNOConfirmGSMCompletedEventHandler(object sender, SendTCNOConfirmGSMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendTCNOConfirmGSMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendTCNOConfirmGSMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendMessageResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendMessageResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CancelMessagesCompletedEventHandler(object sender, CancelMessagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CancelMessagesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CancelMessagesResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591