//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace GK.WindowsServices.ProcessGiftRequest.interlinkService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OperactiveOrderSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StructuralObject))]
    public partial class OperactiveOrder : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback OrderAddOperationCompleted;
        
        private System.Threading.SendOrPostCallback OrderCancelOperationCompleted;
        
        private System.Threading.SendOrPostCallback OrderFinalityOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProductListOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProductDeatilOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProductDetailAvoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OperactiveOrder() {
            this.Url = global::GK.WindowsServices.ProcessGiftRequest.Properties.Settings.Default.GK_WindowsServices_ProcessGiftRequest_interlinkService_OperactiveOrder;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event OrderAddCompletedEventHandler OrderAddCompleted;
        
        /// <remarks/>
        public event OrderCancelCompletedEventHandler OrderCancelCompleted;
        
        /// <remarks/>
        public event OrderFinalityCompletedEventHandler OrderFinalityCompleted;
        
        /// <remarks/>
        public event ProductListCompletedEventHandler ProductListCompleted;
        
        /// <remarks/>
        public event ProductDeatilCompletedEventHandler ProductDeatilCompleted;
        
        /// <remarks/>
        public event ProductDetailAvoCompletedEventHandler ProductDetailAvoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OrderAdd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OrderAdd(
                    string webPassword, 
                    int bussinesPartnerID, 
                    string createDate, 
                    string productCode, 
                    int count, 
                    string address, 
                    string city, 
                    string county, 
                    string cityCode, 
                    string customerName, 
                    string customerSurName, 
                    string phoneAreaCode, 
                    string phoneNumber, 
                    string mobilePhoneAreaCode, 
                    string mobilePhoneNumber, 
                    string customerTitle, 
                    string orderId, 
                    string description, 
                    int catalogId, 
                    string customerCode) {
            object[] results = this.Invoke("OrderAdd", new object[] {
                        webPassword,
                        bussinesPartnerID,
                        createDate,
                        productCode,
                        count,
                        address,
                        city,
                        county,
                        cityCode,
                        customerName,
                        customerSurName,
                        phoneAreaCode,
                        phoneNumber,
                        mobilePhoneAreaCode,
                        mobilePhoneNumber,
                        customerTitle,
                        orderId,
                        description,
                        catalogId,
                        customerCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OrderAddAsync(
                    string webPassword, 
                    int bussinesPartnerID, 
                    string createDate, 
                    string productCode, 
                    int count, 
                    string address, 
                    string city, 
                    string county, 
                    string cityCode, 
                    string customerName, 
                    string customerSurName, 
                    string phoneAreaCode, 
                    string phoneNumber, 
                    string mobilePhoneAreaCode, 
                    string mobilePhoneNumber, 
                    string customerTitle, 
                    string orderId, 
                    string description, 
                    int catalogId, 
                    string customerCode) {
            this.OrderAddAsync(webPassword, bussinesPartnerID, createDate, productCode, count, address, city, county, cityCode, customerName, customerSurName, phoneAreaCode, phoneNumber, mobilePhoneAreaCode, mobilePhoneNumber, customerTitle, orderId, description, catalogId, customerCode, null);
        }
        
        /// <remarks/>
        public void OrderAddAsync(
                    string webPassword, 
                    int bussinesPartnerID, 
                    string createDate, 
                    string productCode, 
                    int count, 
                    string address, 
                    string city, 
                    string county, 
                    string cityCode, 
                    string customerName, 
                    string customerSurName, 
                    string phoneAreaCode, 
                    string phoneNumber, 
                    string mobilePhoneAreaCode, 
                    string mobilePhoneNumber, 
                    string customerTitle, 
                    string orderId, 
                    string description, 
                    int catalogId, 
                    string customerCode, 
                    object userState) {
            if ((this.OrderAddOperationCompleted == null)) {
                this.OrderAddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrderAddOperationCompleted);
            }
            this.InvokeAsync("OrderAdd", new object[] {
                        webPassword,
                        bussinesPartnerID,
                        createDate,
                        productCode,
                        count,
                        address,
                        city,
                        county,
                        cityCode,
                        customerName,
                        customerSurName,
                        phoneAreaCode,
                        phoneNumber,
                        mobilePhoneAreaCode,
                        mobilePhoneNumber,
                        customerTitle,
                        orderId,
                        description,
                        catalogId,
                        customerCode}, this.OrderAddOperationCompleted, userState);
        }
        
        private void OnOrderAddOperationCompleted(object arg) {
            if ((this.OrderAddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OrderAddCompleted(this, new OrderAddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OrderCancel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OrderCancel(string webPassword, int orderId, int BusinesPartnerId) {
            object[] results = this.Invoke("OrderCancel", new object[] {
                        webPassword,
                        orderId,
                        BusinesPartnerId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OrderCancelAsync(string webPassword, int orderId, int BusinesPartnerId) {
            this.OrderCancelAsync(webPassword, orderId, BusinesPartnerId, null);
        }
        
        /// <remarks/>
        public void OrderCancelAsync(string webPassword, int orderId, int BusinesPartnerId, object userState) {
            if ((this.OrderCancelOperationCompleted == null)) {
                this.OrderCancelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrderCancelOperationCompleted);
            }
            this.InvokeAsync("OrderCancel", new object[] {
                        webPassword,
                        orderId,
                        BusinesPartnerId}, this.OrderCancelOperationCompleted, userState);
        }
        
        private void OnOrderCancelOperationCompleted(object arg) {
            if ((this.OrderCancelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OrderCancelCompleted(this, new OrderCancelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OrderFinality", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OrderFinality(string webPassword, int orderId, int BusinesPartnerId) {
            object[] results = this.Invoke("OrderFinality", new object[] {
                        webPassword,
                        orderId,
                        BusinesPartnerId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OrderFinalityAsync(string webPassword, int orderId, int BusinesPartnerId) {
            this.OrderFinalityAsync(webPassword, orderId, BusinesPartnerId, null);
        }
        
        /// <remarks/>
        public void OrderFinalityAsync(string webPassword, int orderId, int BusinesPartnerId, object userState) {
            if ((this.OrderFinalityOperationCompleted == null)) {
                this.OrderFinalityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrderFinalityOperationCompleted);
            }
            this.InvokeAsync("OrderFinality", new object[] {
                        webPassword,
                        orderId,
                        BusinesPartnerId}, this.OrderFinalityOperationCompleted, userState);
        }
        
        private void OnOrderFinalityOperationCompleted(object arg) {
            if ((this.OrderFinalityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OrderFinalityCompleted(this, new OrderFinalityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProductList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public sp_WsCatalogProductList_Result[] ProductList(string webPassword, int CatalogId, int BusinesPartnerId) {
            object[] results = this.Invoke("ProductList", new object[] {
                        webPassword,
                        CatalogId,
                        BusinesPartnerId});
            return ((sp_WsCatalogProductList_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void ProductListAsync(string webPassword, int CatalogId, int BusinesPartnerId) {
            this.ProductListAsync(webPassword, CatalogId, BusinesPartnerId, null);
        }
        
        /// <remarks/>
        public void ProductListAsync(string webPassword, int CatalogId, int BusinesPartnerId, object userState) {
            if ((this.ProductListOperationCompleted == null)) {
                this.ProductListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProductListOperationCompleted);
            }
            this.InvokeAsync("ProductList", new object[] {
                        webPassword,
                        CatalogId,
                        BusinesPartnerId}, this.ProductListOperationCompleted, userState);
        }
        
        private void OnProductListOperationCompleted(object arg) {
            if ((this.ProductListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProductListCompleted(this, new ProductListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProductDeatil", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public sp_WsCatalogProductDetail_Result[] ProductDeatil(string webPassword, int CatalogId, string itemCode, int BusinesPartnerId) {
            object[] results = this.Invoke("ProductDeatil", new object[] {
                        webPassword,
                        CatalogId,
                        itemCode,
                        BusinesPartnerId});
            return ((sp_WsCatalogProductDetail_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void ProductDeatilAsync(string webPassword, int CatalogId, string itemCode, int BusinesPartnerId) {
            this.ProductDeatilAsync(webPassword, CatalogId, itemCode, BusinesPartnerId, null);
        }
        
        /// <remarks/>
        public void ProductDeatilAsync(string webPassword, int CatalogId, string itemCode, int BusinesPartnerId, object userState) {
            if ((this.ProductDeatilOperationCompleted == null)) {
                this.ProductDeatilOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProductDeatilOperationCompleted);
            }
            this.InvokeAsync("ProductDeatil", new object[] {
                        webPassword,
                        CatalogId,
                        itemCode,
                        BusinesPartnerId}, this.ProductDeatilOperationCompleted, userState);
        }
        
        private void OnProductDeatilOperationCompleted(object arg) {
            if ((this.ProductDeatilCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProductDeatilCompleted(this, new ProductDeatilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProductDetailAvo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public sp_WsCatalogProductDetailAvo_Result[] ProductDetailAvo(string webPassword, string itemCode) {
            object[] results = this.Invoke("ProductDetailAvo", new object[] {
                        webPassword,
                        itemCode});
            return ((sp_WsCatalogProductDetailAvo_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void ProductDetailAvoAsync(string webPassword, string itemCode) {
            this.ProductDetailAvoAsync(webPassword, itemCode, null);
        }
        
        /// <remarks/>
        public void ProductDetailAvoAsync(string webPassword, string itemCode, object userState) {
            if ((this.ProductDetailAvoOperationCompleted == null)) {
                this.ProductDetailAvoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProductDetailAvoOperationCompleted);
            }
            this.InvokeAsync("ProductDetailAvo", new object[] {
                        webPassword,
                        itemCode}, this.ProductDetailAvoOperationCompleted, userState);
        }
        
        private void OnProductDetailAvoOperationCompleted(object arg) {
            if ((this.ProductDetailAvoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProductDetailAvoCompleted(this, new ProductDetailAvoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class sp_WsCatalogProductList_Result : ComplexObject {
        
        private System.Nullable<int> katalogIdField;
        
        private string katalogadField;
        
        private string kategoriField;
        
        private int kategoriKodField;
        
        private string urunKodField;
        
        private string markaField;
        
        private string modelField;
        
        private string urunIsimField;
        
        private decimal puanField;
        
        private string infoField;
        
        private string resimField;
        
        private int durumField;
        
        private string buyukResimField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> KatalogId {
            get {
                return this.katalogIdField;
            }
            set {
                this.katalogIdField = value;
            }
        }
        
        /// <remarks/>
        public string Katalogad {
            get {
                return this.katalogadField;
            }
            set {
                this.katalogadField = value;
            }
        }
        
        /// <remarks/>
        public string Kategori {
            get {
                return this.kategoriField;
            }
            set {
                this.kategoriField = value;
            }
        }
        
        /// <remarks/>
        public int KategoriKod {
            get {
                return this.kategoriKodField;
            }
            set {
                this.kategoriKodField = value;
            }
        }
        
        /// <remarks/>
        public string UrunKod {
            get {
                return this.urunKodField;
            }
            set {
                this.urunKodField = value;
            }
        }
        
        /// <remarks/>
        public string Marka {
            get {
                return this.markaField;
            }
            set {
                this.markaField = value;
            }
        }
        
        /// <remarks/>
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public string UrunIsim {
            get {
                return this.urunIsimField;
            }
            set {
                this.urunIsimField = value;
            }
        }
        
        /// <remarks/>
        public decimal Puan {
            get {
                return this.puanField;
            }
            set {
                this.puanField = value;
            }
        }
        
        /// <remarks/>
        public string info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
        
        /// <remarks/>
        public string Resim {
            get {
                return this.resimField;
            }
            set {
                this.resimField = value;
            }
        }
        
        /// <remarks/>
        public int Durum {
            get {
                return this.durumField;
            }
            set {
                this.durumField = value;
            }
        }
        
        /// <remarks/>
        public string BuyukResim {
            get {
                return this.buyukResimField;
            }
            set {
                this.buyukResimField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sp_WsCatalogProductDetailAvo_Result))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sp_WsCatalogProductDetail_Result))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sp_WsCatalogProductList_Result))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class ComplexObject : StructuralObject {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComplexObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sp_WsCatalogProductDetailAvo_Result))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sp_WsCatalogProductDetail_Result))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sp_WsCatalogProductList_Result))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class StructuralObject {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class sp_WsCatalogProductDetailAvo_Result : ComplexObject {
        
        private int idField;
        
        private int itemImageIDField;
        
        private string markaField;
        
        private string modelField;
        
        private string urunIsimField;
        
        private string infoField;
        
        private string resimField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int itemImageID {
            get {
                return this.itemImageIDField;
            }
            set {
                this.itemImageIDField = value;
            }
        }
        
        /// <remarks/>
        public string Marka {
            get {
                return this.markaField;
            }
            set {
                this.markaField = value;
            }
        }
        
        /// <remarks/>
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public string UrunIsim {
            get {
                return this.urunIsimField;
            }
            set {
                this.urunIsimField = value;
            }
        }
        
        /// <remarks/>
        public string info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
        
        /// <remarks/>
        public string Resim {
            get {
                return this.resimField;
            }
            set {
                this.resimField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class sp_WsCatalogProductDetail_Result : ComplexObject {
        
        private System.Nullable<int> katalogIdField;
        
        private string katalogadField;
        
        private string kategoriField;
        
        private int kategoriKodField;
        
        private string urunKodField;
        
        private string markaField;
        
        private string modelField;
        
        private string urunIsimField;
        
        private decimal puanField;
        
        private string infoField;
        
        private string resimField;
        
        private int durumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> KatalogId {
            get {
                return this.katalogIdField;
            }
            set {
                this.katalogIdField = value;
            }
        }
        
        /// <remarks/>
        public string Katalogad {
            get {
                return this.katalogadField;
            }
            set {
                this.katalogadField = value;
            }
        }
        
        /// <remarks/>
        public string Kategori {
            get {
                return this.kategoriField;
            }
            set {
                this.kategoriField = value;
            }
        }
        
        /// <remarks/>
        public int KategoriKod {
            get {
                return this.kategoriKodField;
            }
            set {
                this.kategoriKodField = value;
            }
        }
        
        /// <remarks/>
        public string UrunKod {
            get {
                return this.urunKodField;
            }
            set {
                this.urunKodField = value;
            }
        }
        
        /// <remarks/>
        public string Marka {
            get {
                return this.markaField;
            }
            set {
                this.markaField = value;
            }
        }
        
        /// <remarks/>
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public string UrunIsim {
            get {
                return this.urunIsimField;
            }
            set {
                this.urunIsimField = value;
            }
        }
        
        /// <remarks/>
        public decimal Puan {
            get {
                return this.puanField;
            }
            set {
                this.puanField = value;
            }
        }
        
        /// <remarks/>
        public string info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
        
        /// <remarks/>
        public string Resim {
            get {
                return this.resimField;
            }
            set {
                this.resimField = value;
            }
        }
        
        /// <remarks/>
        public int Durum {
            get {
                return this.durumField;
            }
            set {
                this.durumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void OrderAddCompletedEventHandler(object sender, OrderAddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrderAddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OrderAddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void OrderCancelCompletedEventHandler(object sender, OrderCancelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrderCancelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OrderCancelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void OrderFinalityCompletedEventHandler(object sender, OrderFinalityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrderFinalityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OrderFinalityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ProductListCompletedEventHandler(object sender, ProductListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProductListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProductListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public sp_WsCatalogProductList_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((sp_WsCatalogProductList_Result[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ProductDeatilCompletedEventHandler(object sender, ProductDeatilCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProductDeatilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProductDeatilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public sp_WsCatalogProductDetail_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((sp_WsCatalogProductDetail_Result[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ProductDetailAvoCompletedEventHandler(object sender, ProductDetailAvoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProductDetailAvoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProductDetailAvoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public sp_WsCatalogProductDetailAvo_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((sp_WsCatalogProductDetailAvo_Result[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591